language: go
sudo: required
dist: trusty
go:
  - 1.12

branches:
  only:
    - develop
    - master
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/

notifications:
email: false

env:
  global:
    - GO111MODULE=on
    - CLOUD_SDK_HOME=$HOME/google-cloud-sdk
    - GCS_RELEASE_DIR=gs://boxops/dockcmd/releases

before_install:
  - openssl aes-256-cbc -K $encrypted_e6151bb8a898_key -iv $encrypted_e6151bb8a898_iv -in travis-service-account.json.enc -out travis-service-account.json -d
  - build/install-cloudsdk.sh 241.0.0 $HOME

script: make release

cache:
  directories:
   - $CLOUD_SDK_HOME

after_script:
  - $CLOUD_SDK_HOME/bin/gcloud auth activate-service-account --key-file=./travis-service-account.json;
    cd ./release;
    $CLOUD_SDK_HOME/bin/gsutil -m -q cp -r -a public-read . $GCS_RELEASE_DIR/;
